### ISSUE TITLE
JavaLibCHelper emits illegal reflective access warnings on Java 9

### ISSUE THREAD

**Issue by eregon** [jnr/jnr-posix#108]
JavaLibCHelper emits warnings on Java 9:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:...jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

```
$ java --illegal-access=warn ...  
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/home/eregon/code/java9-ws/truffleruby/mxbuild/dists/truffleruby.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/home/eregon/code/java9-ws/truffleruby/mxbuild/dists/truffleruby.jar) to field sun.nio.ch.FileChannelImpl.fd
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/home/eregon/code/java9-ws/truffleruby/mxbuild/dists/truffleruby.jar) to field java.io.FileDescriptor.fd
```

The first two are only used by `getDescriptorFromChannel()` which is only used in tests.
Maybe we can just make that a private helper for tests? But not sure if somebody actually uses this helper.

The last one (`FileDescriptor.fd`) is used in tests but also for `fstat()` and other libc functions taking a FileDescriptor.

What would be a good option to fix these warnings?
I am thinking maybe just check for Java 9 and in such a case just set them to `null` as if there was a SecurityException.
Or maybe move those in a separate class so they only load on first usage.
In the case of TruffleRuby, we have fds as `int` so these methods taking `FileDescriptor` instances are never used I believe.

cc @headius @chrisseaton

**Comment by headius** [comment]
Released in 3.0.42.
