### ISSUE TITLE
Source headers inconsistent with License.Txt

### ISSUE THREAD

**Issue by brianf** [jnr/jnr-posix#115]
The license.txt file describes an EPL/GPL/LGPL tri license, however all the source headers describe CPL/GPL/LGPL. GIven that, the license is actually unclear.

**Comment by headius** [comment]
CPL is transparently upgradable to EPL, so I guess we just missed some references when we upgraded. I'll fix that.

**Comment by headius** [comment]
Fixed in 7cb93b0.
