### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by ennru** [jnr/jnr-posix#119]
Thank you for the great work in this library!

Our license checker for Akka Alpakka reacted on the license information and when I look at @headius commit to update the license name from Common Public License to Eclipse Public License, I wonder which version of EPL it is supposed to be.
The `pom.xml` and `LICENSE.txt` state EPL 1.0, but all file headers EPL 2.0.

https://github.com/jnr/jnr-posix/commit/7cb93b0f4a1592498c4b6e75f4fb2acf99bfdddb#diff-600376dffeb79835ede4a0b285078036

**Comment by headius** [comment]
Ahh, thanks for the catch! Yes, it should be EPL 2.0 everywhere. I'll fix the files you mentioned.

**Comment by headius** [comment]
Oh my I opened this bug without looking at what project it was filed against...I see that jnr-posix does indeed have a few references to EPL 1.0.

**Comment by headius** [comment]
Should be all set now. The text of the EPL 1.0 was in LICENSE.txt *three times*!

Let us know if you have any other issues!
