### ISSUE TITLE
Improve BSD support

### ISSUE THREAD

**Issue by headius** [jnr/jnr-posix#134]
There are a number of outstanding BSD support items from jffi on up. This issue is a catch-all for these outstanding items so we can discuss them in one place.

#126 has some discussion and many of the original links for these issues.

I just merged #132 from @Freaky for FreeBSD struct support, and #127 for support for DragonFly BSD by @tuxillo.

@smortex has submitted #133, jnr/jffi#66, and jnr/jnr-ffi#189 for review.

**Comment by headius** [comment]
Other @tuxillo Dragonfly BSD PRs: jnr/jffi#64, jnr/jnr-ffi@184

**Comment by tuxillo** [comment]
Thanks @headius. Let me know if you want me to test anything.

**Comment by headius** [comment]
@tuxillo With all these different platforms, I'm starting to wish we had a better cross-platform test matrix.

**Comment by headius** [comment]
@tuxillo I have merged jnr/jffi#64. Do we need to build binaries? Once this and jnr/jffi#66 is in I'll look at putting out a jffi release and then moving up the stack.

**Comment by tuxillo** [comment]
Yeah, I belive it will need binaries. I've left a comment in https://github.com/jnr/jffi/pull/64 as well.

With regards to the text matrix I am afraid my Java skills are quite basic. However, I'm willing to help with testing etc in this platform. We can also provide build bots for it if needed (self-hosted, not in the cloud for now).

**Comment by headius** [comment]
I believe we did get DragonflyBSD binaries in so this should have been closed. See jnr/jffi#77.

**Comment by headius** [comment]
Binaries were merged to jffi in 1.2.22. jnr-ffi was updated in 2.1.11 (weird coincidental numbering there) which was then used in jnr-posix 3.0.51.
