### ISSUE TITLE
Update jnr-constants to get arch support

### ISSUE THREAD

**Issue by headius** [jnr/jnr-posix#166]
In jnr/jnr-constants#98 we learned that arch-specific constant support is already working and just needed those files generated into appropriate locations. This makes the change from #145 reversible, once we upgrade to a newer jnr-constants that has Linux/ppc-specific values.

This issue is a placeholder for doing that update, which I will start experimenting with in a separate PR.

We should also add some additional tests for other POSIX APIs that depend on constants with arch-specific values (such as those @shanjiantao fixed in jnr/jnr-constants#98).

**Comment by headius** [comment]
@shanjiantao I suppose we could also set up qemu **test** builds for jnr-posix to really make sure we are testing the platforms we need to test.

**Comment by shanjiantao** [comment]
I agree that it's necessery to run tests with qemu, I suppose we can keep the current `test and build` while adding additional qemu tests. In other words, we could use qemu as an option. After all, we should consider that most situations do not care multi-architecture.
