### ISSUE TITLE
Ask for Java 21 support for com.github.jnr : jnr-posix

### ISSUE THREAD

**Issue by Swarn10** [jnr/jnr-posix#191]
### If there are plans already to support Java 21, is there an ETA for the same?

**Comment by headius** [comment]
Hello! I believe there's no reason jnr-posix should not work on Java 21, provided the appropriate module `--add-opens` flags are passed for it to access JDK internals. Do you have a specific issue?

**Comment by headius** [comment]
No follow-up and jnr-posix should already work fine on Java 21.
