### ISSUE TITLE
dev_major and dev_minor on Windows

### ISSUE THREAD

**Issue by djberg96** [jnr/jnr-posix#23]
It appears that the dev_major, dev_minor, rdev_major and rdev_minor methods from the File::Stat class try to return numeric values on MS Windows. It seems they're using the results of the dev and rdev methods, which return a drive number (0, 1, or 2 for A:, B: or C: drives, for example). The dev and rdev methods themselves are fine - that matches MRI.

However, in MRI these methods all return nil as these have no meaningful value on Windows.

**Comment by headius** [comment]
This is really a JRuby issue, isn't it? Closing. If it's a JRuby issue we still need to address, reopen there please.

**Comment by djberg96** [comment]
@headius I don't remember now, but I'm pretty sure you or someone on #jruby told me to put it here. :)

In any case, these methods now return nil as expected, at least as of 9.0.0.5, so it's a non-issue.
