### ISSUE TITLE
gethostname() not implemented

### ISSUE THREAD

**Issue by dmlloyd** [jnr/jnr-posix#29]
The gethostname() function is in the POSIX manual, however it is not specified in the project's POSIX interface (and also is annoyingly not present in the JDK itself).

This might be a useful addition; also it should be fairly trivial to add.

**Comment by kervinpierre** [comment]
Merging this would be nice if it is complete.

**Comment by tomasol** [comment]
I would like this to be merged also.

**Comment by tomasol** [comment]
Actually I found out that the previous implementation was segfaulting. I will create a new pull request.
