### ISSUE TITLE
Ability to disable fallback to JavaPOSIX

### ISSUE THREAD

**Issue by johngmyers** [jnr/jnr-posix#42]
I would like a way to get `POSIXFactory` to handle failure to load the native POSIX by propagating the `Throwable`, not returning a `JavaPOSIX`.

The caller cannot function with the limited functionality of `JavaPOSIX`. It would be better to fail fast with a useful exception than to delay failure with an uninformative "not implemented" error.

**Comment by headius** [comment]
Agreed...this should be added.
