### ISSUE TITLE
JavaSecuredFile has a Google copyright

### ISSUE THREAD

**Issue by headius** [jnr/jnr-posix#45]
JavaSecuredFile.java was added by @olabini in (commit redacted to reduce tainting potential) with an appropriately tri-licensed header but a Google copyright. We can't trace the lineage of this file, because it appeared all at once and does not appear to exist anywhere else in the world.

@olabini Was the Google copyright a mistake here, or did you actually get this from some Google code?

This is a blocker for some folks planning to embed jnr-posix.

NOTE: Anyone attempting to use my clean-room description below to reimpl this file MUST NOT have ever seen the original. So don't go looking for it.

**Comment by olabini** [comment]
Ouch. Hmm. If the Google copyright is there, it is there for a reason. It is very strange though, since the rest of the license is ours. My guess is that this file originated in one of the other repos (maybe even JRuby proper) and was contributed originally by one of the Google contributors. I suspect my role was just moving it.

**Comment by olabini** [comment]
I think the easiest choice might be to describe the functionality to someone who haven't seen the code, and have them reimplement it - it's fairly basic stuff.

**Comment by headius** [comment]
Yeah I think you're right. I'll figure out some way to replace this.

**Comment by headius** [comment]
My description of the file in question:

Description of JavaSecuredFile and its behavior.

* Extends java.io.File.
* Class is public and non-final.
* All methods public.
* Overrides all constructors but passes args through unmodified.
* Overrides getParentFile to call getParent, wrapping the non-null result as a new JavaSecuredFile or returning null.
* Overrides getAbsoluteFile to call getAbsolutePath, same wrapping as above.
* Overrides getCanonicalFile to call getAbsolutePath, same wrapping as above.
* Overrides the following methods to call their super version, catching SecurityException and returning false: canRead, canWrite, exists, isDirectory, isFile, isHidden, delete, mkdir, mkdirs, renameTo, setLastModified, setReadOnly
* Overrides the following methods to call their super versions, catching SecurityException and re-throwing it inside an IOException: getCanonicalPath, createNewFile
* Overrides the following methods to call their super versions, catching SecurityException and returning null: list(), list(FilenameFilter), listFiles(), listFiles(FilenameFilter), listFiles(FileFilter)
* Overrides the following methods to call their super versions, catching SecurityException and returning 0L: lastModified, length

**Comment by solidline** [comment]
Taking a stab at it now.

**Comment by headius** [comment]
@solidline I may have a working version from @timyates already...

**Comment by solidline** [comment]
@headius ok sounds good.

**Comment by timyates** [comment]
:smiley_cat: 

[Here's my version from the description in a gist](https://gist.github.com/timyates/b3cae0cddda8b6c832b6)

**Comment by solidline** [comment]
I was almost done, decided to finish it: https://gist.github.com/solidline/bef651d7d7596c03a1b2

**Comment by shartley** [comment]
My version:
Suppresses serialization warning and assumes typo in spec above for getCanonicalFile.
https://gist.github.com/3ef30e80e42c30dc7de4.git

**Comment by headius** [comment]
@shartley Good catch on getCanonicalFile...I fixed the description.

**Comment by timyates** [comment]
And I had mine wrong, as I was calling `super.getCanonicalFile()` then wrapping that in a `JavaSecuredFile(file, "")` which didn't match the spec...  Updated now, but there's no point being fast and wrong :frowning:

**Comment by headius** [comment]
@timyates got his in first, so I'm going to use that as a baseline and apply the additional fixes from @shartley. As expected, these are all nearly identical so I don't think there's anything in @solidline's version that's different :-)

Anyway, you guys are all aces in my book...thank you for helping.

@timyates Please reply saying you never saw the original source of JavaSecuredFile.java and you consent to having your version licensed under our CPL/GPL/LGPL tri-license.

@shartley You too.

**Comment by timyates** [comment]
I never saw the original source of JavaSecuredFile, based all of the code on the above description of requirements, and I gladly consent to having my version licensed under the CPL/GPL/LGPL tri-license

Glad I could help :-)

**Comment by shartley** [comment]
Non clean room version:

I never saw the original source of JavaSecuredFile, based all of the code on the above description of requirements, and I gladly consent to having my version licensed under the CPL/GPL/LGPL tri-license

**Comment by timyates** [comment]
lol ;-)

**Comment by shartley** [comment]
@tinymates Does your update break the expected wrapping behaviour and not return null when it should?

**Comment by headius** [comment]
@shartley I noticed that when I started running tests, so I reversed course and went with yours. I could have just fixed it but I figured anything more than trivial changes might be frowned on since I'm tainted.

**Comment by headius** [comment]
This is now fixed. The reimpl was done by multiple people, but the version we have is based on @shartley's clean room reimplementation based on my spec above. I did a couple commits after the replacement to tidy up formatting and a couple compile-time issues and spec differences.

**Comment by shartley** [comment]
Cool. I'll try to remain untainted, just-in-case!

**Comment by timyates** [comment]
Me too

@shartley yes it does *sigh* I have nothing to blame either, apart from myself.. PS: @tinymates -- Lol!
