### ISSUE TITLE
Please add dup function

### ISSUE THREAD

**Issue by bjfish** [jnr/jnr-posix#51]
Reference: http://pubs.opengroup.org/onlinepubs/009695399/functions/dup.html

This is used in io.rb

**Comment by nirvdrum** [comment]
`dup` and `dup2` should already be implemented. You can see tests for them in [FileTest](https://github.com/jnr/jnr-posix/blob/master/src/test/java/jnr/posix/FileTest.java#L102-L144).  What problem are you seeing?

**Comment by bjfish** [comment]
@nirvdrum my mistake then, closing this issue...
