### ISSUE TITLE
Add posix_fadvise

### ISSUE THREAD

**Issue by bjfish** [jnr/jnr-posix#52]
Please add posix_fadvise along with constant values for the permissible values:
http://linux.die.net/man/2/posix_fadvise

**Comment by headius** [comment]
Can you help?

**Comment by bjfish** [comment]
@headius What are the steps/ a good example on how to add a posix function to jnr-posix?

cc: @nirvdrum

**Comment by nirvdrum** [comment]
If you look through the commit history, you can see some of the POSIX methods I've added. I've kept the commits fairly clean, so they should serve as a good template.

If you do need new constants, however, you'll need to work with the jnr-constants project and that one is a bit more involved. There are platform-specific constants and the simplest way to get them is to run a tool that ships within jnr-constants that figures the values out. You can supply the fallover defaults should the native ones not have been generated, but it'd be best to try to coordinate with people that have access to each of the native environments so we can ensure they have correct values.

**Comment by headius** [comment]
To clarify slightly... we'll take a single-platform constant set for most POSIX constants, since they tend not to vary much across platforms. Due diligence is recommended, though: if you see online that other platforms vary a lot, it would obviously be best to get them generated.
