### ISSUE TITLE
Add getrlimit and setrlimit

### ISSUE THREAD

**Issue by bjfish** [jnr/jnr-posix#53]
Please add `getrlimit` and `setrlimit`
http://pubs.opengroup.org/onlinepubs/009695399/functions/getrlimit.html

**Comment by bjfish** [comment]
cc: @nirvdrum FYI I added another POSIX issue "getrlimit and setrlimit", in case your can add this.

**Comment by chrisseaton** [comment]
If you need these in Truffle you can just create your own interface for them like we did with NativeSockets.

**Comment by nirvdrum** [comment]
I've implemented both of these in ce7377190b5aa1c920f70cb112af12f9a0d78a87 and b4ac963ed9389aaffb03248421c3235e8eaba85c.
