### ISSUE TITLE
maven package command fails because GroupTest.java fails

### ISSUE THREAD

**Issue by nduane** [jnr/jnr-posix#63]
First of all I'm a Linux/Java/GIT newbie.  I just pulled your jnr-posix package down to my Fedora 21 desktop and then ran 'mvn package'.  That had a test failure and I guess a single test failure also causes a failure in generating the jar.  I did some searching and found:

http://pkgs.fedoraproject.org/cgit/jnr-posix.git/commit/?h=f22

Not quite sure what that link is.  I guess you're doing some work with the Fedora project?  At any rate I saw the comment about changing 'nogroup' to 'root' in GroupTest.java so I made the change on the source I pulled down.  That fixed the build.  I guess you should fix GroupTest.java on github.

Thanks,
Nick

**Comment by headius** [comment]
Does this still fail? We've set up linux CI builds since this report...
