### ISSUE TITLE
FindFirstFileW on 32 bit JVM crashes

### ISSUE THREAD

**Issue by enebo** [jnr/jnr-posix#69]
we have a FIXME: shortcutting WindowsPOSIX.stat to call win32's posix stat fallback.  This is undesirable since it does not support UNC nor long paths.  If I remove this work around in cases where GetFileAttributesExW fails we crash in fallback call to FindFirstFileW.

The crash itself appears to be us populating something incorrectly but windows itself seems very good at not changing word sizes between 32/64 so I am baffled by 32 fails and 64 works.

**Comment by headius** [comment]
Didn't you figure out what was actually causing this, @enebo?

**Comment by enebo** [comment]
@headius yeah this is fixed already.
