### ISSUE TITLE
lseek return type should be long on 64 bit platforms

### ISSUE THREAD

**Issue by byteit101** [jnr/jnr-posix#71]
off_t is a long on 64 bit platforms, but the POSIX interface lists it as an int. It should be updated to match the platform size on x86_64 systems. Discovered via https://github.com/jruby/jruby/issues/3664

**Comment by headius** [comment]
We should add new versions of these, since changing the return value is not compatible. I guess the most logical name would be `lseekLong`. Want to through together a quick PR?
