### ISSUE TITLE
SpawnFileAction.open opens wrong filename

### ISSUE THREAD

**Issue by rbrewer** [jnr/jnr-posix#78]
I have a problem with jnr-posix-3.0.29 running on CentOS 7 using JDK 1.8. I'm trying to spawn processes using posix_spawnp, with stdout redirected to a file. Unfortunately, it looks like the filename I provide to SpawnFileAction.open is not honored, and the output is written to a randomly named file (usually with unprintable characters) in the current directory.

I have created a [minimum working example](https://github.com/rbrewer/posix_spawn_test) that shows the problem. One directory has working C code that does what I want, the other directory has Java JNR code that exhibits the problem.

Using `strace`, the C code file open looks something like this:
`open("/tmp/foo-log", O_WRONLY|O_CREAT|O_TRUNC, 0644)              = 3`
while the JNR code produces strace output like this:
`open("\300\216mu;\177", O_WRONLY|O_CREAT|O_TRUNC, 0644) = 12` where that first parameter should be `/tmp/bar-log`. Could the filename be uninitialized memory?

Any thoughts on what the problem might be? I have single-stepped the code in Eclipse, and on the Java side it looked reasonable. On the `posix_spawn_file_actions_addopen` man page I saw this tidbit: "The string described by path shall be copied by the posix_spawn_file_actions_addopen() function." not sure if that is relevant.

P.S.  To clean up the files with unprintable names `ls -lb` and `rm $'filename'` are helpful :)

**Comment by headius** [comment]
This looks like an encoding problem. Are you on an environment with a peculiar filesystem encoding?

**Comment by headius** [comment]
A few other things you can check:

* What is the value of file.encoding Java property?
* What is the default Charset (Charset.defaultCharset() I believe)?

**Comment by rbrewer** [comment]
We have worked around the bug by doing a POSIX.open on the desired output file, and then dup stdin and stderr to the new file descriptor. With this change, posix_spawn directs stdin/err as expected, so looks like it's not an encoding issue.

**Comment by aardvark179** [comment]
I've hit this exact issue on Oracle Linux (which is derived from CentOS). The problem appears to be that `posix_spawn_file_actions_addopen` is not performing a `strdup` on the path as required by the POSIX standard. This was fixed in https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=89e435f3559c53084498e9baad22172b64429362 in mid 2014, and the patch has not been applied to the 2.18 glibc in centos. You can recreate the issue using the following C program (derived from @rbrewer's).
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <spawn.h>
#include <unistd.h>

int main(int argc, char* argv[], char *env[])
{
  int ret, i;
  pid_t child_pid;
  char *path = strdup("/tmp/foo-log");
  posix_spawn_file_actions_t child_fd_actions;
  ret = posix_spawn_file_actions_init (&child_fd_actions);
  if (ret)
    perror ("posix_spawn_file_actions_init"), exit(ret);
  ret = posix_spawn_file_actions_addopen (&child_fd_actions, 1, path, 
                                          O_WRONLY | O_CREAT | O_TRUNC, 0644);
  if(ret)
    perror ("posix_spawn_file_actions_addopen"), exit(ret);
  char *args[3] = {"echo", "foo", NULL};
  path[5] = 'b';
  ret = posix_spawnp (&child_pid, "echo", &child_fd_actions, NULL, args, env);
  if(ret)
    perror ("posix_spawn"), exit(ret);
  printf("child pid: %d\n", child_pid);
}
```
Which will log to either `/tmp/foo-log` or `/tmp/boo-log` depending on whether the path has been copied or not.
I think this might also be the reason `SpawnTest#inputFile()` is commented out as failing on Travis.

**Comment by headius** [comment]
@aardvark179 I apparently never saw this comment, but since this was never broken I will close it. I have reenabled the SpawnTest and it passes on GHA.
