### ISSUE TITLE
read/write methods restrict number of bytes to 32 bit

### ISSUE THREAD

**Issue by ahilananantha** [jnr/jnr-posix#84]
AFAICT the underlying read(), write(), pread(), and pwrite() are supposed to be able to accept size_t as number of bytes argument and return ssize_t for number of bytes written. But the POSIX class is restricting the values to 32 bit Java int. Also the offset arguments for pread() and pread() are of type off_t which is often 64 bit.

**Comment by headius** [comment]
Indeed! Many of the jnr-posix methods were unfortunately written with 32-bit arguments and return values. It should be easy enough to add the long versions of these IO methods, though...want to try your hand at a PR?

**Comment by ahilananantha** [comment]
So you're suggesting just overloading the methods to avoid breaking backward compatibility with code that expects an int return value? I'll make an attempt to add those in and replicate the test code in IOTest.java.
