### ISSUE TITLE
SEGV due to posix_spawnattr_init called on a too small allocation

### ISSUE THREAD

**Issue by eregon** [jnr/jnr-posix#96]
https://github.com/jnr/jnr-posix/blob/e24762456ae8728b16bcc7ed773952069fbfc039/src/main/java/jnr/posix/BaseNativePOSIX.java#L588 expects `sizeof(posix_spawnattr_t)` to be <= 128.

But on my system (`Linux localhost.localdomain 4.9.4-100.fc24.x86_64 #1 SMP Tue Jan 17 19:08:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`):

```c
#include <stdio.h>
#include <spawn.h>

int main() {
	printf("posix_spawn_file_actions_t: %ld\n", sizeof(posix_spawn_file_actions_t));
	printf("posix_spawnattr_t: %ld\n", sizeof(posix_spawnattr_t));
	return 0;
}
```
prints:
```
posix_spawn_file_actions_t: 80
posix_spawnattr_t: 336
```

How should this be dealt with?
Is there a way to get the value of `sizeof(posix_spawnattr_t)` per platform?

**Comment by eregon** [comment]
The corresponding commit in TruffleRuby was revered for safety: https://github.com/graalvm/truffleruby/commit/893db3f0278ae68827dac5792ad765cf75d8f915

**Comment by headius** [comment]
We just need to right-size the memory for platforms where it differs.

**Comment by eregon** [comment]
Right, so how can we get the value of `sizeof(posix_spawnattr_t)` in JNR?

**Comment by headius** [comment]
The short answer is that we just figure out that value and override the allocation for Linux to use it.

Look at the other platform-specific POSIX impls. There's many examples of sizing memory and specializing structs.

**Comment by headius** [comment]
And if it differs on other platforms we should add overrides for them too.

**Comment by eregon** [comment]
@headius Thanks, I created #97 following the allocateStat approach.

**Comment by headius** [comment]
Released.
